import * as Joi from 'joi';

export const validationConfigSchema = Joi.object({
  PORT: Joi.number().default(3000),
  STAGE: Joi.string().required(),
  PP_DB_HOST: Joi.string().required(),
  PP_DB_PORT: Joi.number().default(5432).required(),
  PP_DB_USERNAME: Joi.string().required(),
  PP_DB_DATABASE: Joi.string().required(),
  NODE_DB_HOST: Joi.string().required(),
  NODE_DB_PORT: Joi.string().required(),
  NODE_DB_USERNAME: Joi.string().required(),
  NODE_DB_PASSWORD: Joi.string().required(),
  NODE_DB_DATABASE: Joi.string().required(),
  POKTSCAN_V2_API_KEY: Joi.string().required(),
  JWT_ACCESS_TOKEN_SECRET: Joi.string().required(),
  JWT_REFRESH_TOKEN_SECRET: Joi.string().required(),
  TWO_FACTOR_AUTHENTICATION_APP_NAME: Joi.string().required(),
  JWT_EMAIL_VERIFICATION_TOKEN_SECRET: Joi.string().required(),
  JWT_EMAIL_VERIFICATION_TOKEN_EXPIRY: Joi.number().required(),
  JWT_PASSWORD_RESET_TOKEN_SECRET: Joi.string().required(),
  JWT_PASSWORD_RESET_TOKEN_EXPIRY: Joi.number().required(),
  JUMIO_USERNAME: Joi.string().required(),
  JUMIO_PASSWORD: Joi.string().required(),
  GOOGLE_RECAPTCHA_SECRET_KEY: Joi.string().required(),
  DISCORD_BOT_TOKEN: Joi.string().required(),
  SENDGRID_API_KEY: Joi.string().required(),
  AWS_ACCESS_KEY_ID: Joi.string().required(),
  AWS_SECRET_ACCESS_KEY: Joi.string().required(),
  S3_ACCESS_KEY_ID: Joi.string().required(),
  S3_SECRET_ACCESS_KEY: Joi.string().required(),
});
