// Status Enum

export enum StakeStatus {
  TRANSACTION_VERIFIED_AWAITING_STAKE = 0,
  TRANSACTION_FAILED = 1,
  TRANSACTION_DOES_NOT_EXIST = 2,
  AWAITING_VALIDATION = 3,
  TRANSACTION_STAKED = 4,
  USER_WALLET_MISMATCH = 5,
  TRANSACTION_DESTINATION_MISMATCH = 6,
  TRANSACTION_NOT_FOUND_24 = 7,
  INSUFFICIENT_FUNDS = 10,
}
