export enum CONTACT_CHANNEL {
  EMAIL = 6,
}

export enum CONTACT_TYPE {
  TRANSFER_RECEIVED = 5,
  WALLET_VERIFICATION = 1,
  STAKING_VERIFICATION = 2,
  UNSTAKE_SENT = 3,
  SWEEP_SENT = 4,
  MONTHLY_STATEMENT = 13,
}
